### PR TITLE
Get ci pipeline green with tests

### PR DESCRIPTION
**Pull request by magrathj**
* got unit tests running
* Couldnt get it running for mac and linux

### CODE REVIEW

**Comment by magrathj** [comment]
@francisco-ltech  - do you know how to make these commands run on mac/linux?


# MakeFile

build_utilities:
	python .\src\utilities\setup.py develop

install_utilities:
	pip install .\src\utilities\

**Comment by francisco-ltech** [comment]
@magrathj  Which app do you use to run makefile in Windows?

**Comment by magrathj** [comment]
@francisco-ltech  just run the make command, not sure which package its running. But its the commands underneath which are failing on linux and mac agents.

python .\src\utilities\setup.py develop

pip install .\src\utilities\

**Comment by francisco-ltech** [comment]
@magrathj It's not the command itself, it fails because of the path separator, you are using Windows back slack convention, *nix systems use forward slash convention. What do you use on Windows? git bash should be able to handle forward slash.

**Pull request merged**
